name: Create Archive
on:
  push:
     tags:
       - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      mission1: test.miz
    steps:
      - name: Checkout main
        uses: actions/checkout@main
      #### test.miz ####
      - name: Create zip
        uses: thedoctor0/zip-release@0.7.0
        with:
          type: "zip"
          filename: "$mission1"
          directory: "tests/$mission1"
      - name: Add to release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "tests/$mission1/$mission1"
          removeArtifacts: "true"
          allowUpdates: "true"
