name: Create Archive
on: 
  push:
    tags:
      - '*'
   # branches:
   #   - main

jobs:
  build:    
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout main
        uses: actions/checkout@main      
      # - name: action-zip              
      #   uses: montudor/action-zip@v1.0.0        
      #   with:
      #     # See montudor/action-zip README.md for more info
      #     args: zip -qq -r test.miz .
      - name: zip release
        uses: thedoctor0/zip-release@0.7.0
          with:
            type: "zip"
            filename: "test.miz"
            directory: "tests/test.miz"
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0        
        with:
          artifacts: "tests/test.miz/test.miz"
