name: Create Archive
on: 
  push:
    tags:
      - '*'
   # branches:
   #   - main

jobs:
  build:    
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: checkout main
        uses: actions/checkout@main      
      - name: test.miz
        run: cd tests/test.miz
      - name: action-zip        
      # You may pin to the exact commit or the version.
      # uses: montudor/action-zip@0852c26906e00f8a315c704958823928d8018b28
        uses: montudor/action-zip@v1.0.0
        with:
          # See montudor/action-zip README.md for more info
          args: zip -qq -r test.miz .
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "test.miz"
